apiVersion: skaffold/v1beta3
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: sample-app/app-dev
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - kubernetes/app/*
