apiVersion: v1
kind: ConfigMap
metadata:
  name: api-nginx-conf
data:
  nginx.conf: |
    server {
        listen       443 ssl;
        server_name  sample-api-service.default.svc.cluster.local;
        ssl_certificate /etc/tls/nginx-selfsigned.crt;
        ssl_certificate_key /etc/tls/nginx-selfsigned.key;

        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        # ssl_ciphers HIGH:!aNULL:!MD5;
        # ssl_prefer_server_ciphers on;

        # ssl_session_cache shared:SSL:10m;
        # ssl_session_timeout 10m;

        location / {
            root   /var/www/laravel/public;
            try_files $uri /index.php?$query_string;
        }
    }
